/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Thrift.Test
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class ListBonks : TBase
  {
    private List<Bonk> _bonk;

    public List<Bonk> Bonk
    {
      get
      {
        return _bonk;
      }
      set
      {
        __isset.bonk = true;
        this._bonk = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool bonk;
    }

    public ListBonks() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.List) {
                {
                  Bonk = new List<Bonk>();
                  TList _list133 = iprot.ReadListBegin();
                  for( int _i134 = 0; _i134 < _list133.Count; ++_i134)
                  {
                    Bonk _elem135;
                    _elem135 = new Bonk();
                    _elem135.Read(iprot);
                    Bonk.Add(_elem135);
                  }
                  iprot.ReadListEnd();
                }
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("ListBonks");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (Bonk != null && __isset.bonk) {
          field.Name = "bonk";
          field.Type = TType.List;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          {
            oprot.WriteListBegin(new TList(TType.Struct, Bonk.Count));
            foreach (Bonk _iter136 in Bonk)
            {
              _iter136.Write(oprot);
            }
            oprot.WriteListEnd();
          }
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("ListBonks(");
      bool __first = true;
      if (Bonk != null && __isset.bonk) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Bonk: ");
        __sb.Append(Bonk);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
