/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Thrift.Test
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class NestedListsI32x3 : TBase
  {
    private List<List<List<int>>> _integerlist;

    public List<List<List<int>>> Integerlist
    {
      get
      {
        return _integerlist;
      }
      set
      {
        __isset.integerlist = true;
        this._integerlist = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool integerlist;
    }

    public NestedListsI32x3() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.List) {
                {
                  Integerlist = new List<List<List<int>>>();
                  TList _list91 = iprot.ReadListBegin();
                  for( int _i92 = 0; _i92 < _list91.Count; ++_i92)
                  {
                    List<List<int>> _elem93;
                    {
                      _elem93 = new List<List<int>>();
                      TList _list94 = iprot.ReadListBegin();
                      for( int _i95 = 0; _i95 < _list94.Count; ++_i95)
                      {
                        List<int> _elem96;
                        {
                          _elem96 = new List<int>();
                          TList _list97 = iprot.ReadListBegin();
                          for( int _i98 = 0; _i98 < _list97.Count; ++_i98)
                          {
                            int _elem99;
                            _elem99 = iprot.ReadI32();
                            _elem96.Add(_elem99);
                          }
                          iprot.ReadListEnd();
                        }
                        _elem93.Add(_elem96);
                      }
                      iprot.ReadListEnd();
                    }
                    Integerlist.Add(_elem93);
                  }
                  iprot.ReadListEnd();
                }
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("NestedListsI32x3");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (Integerlist != null && __isset.integerlist) {
          field.Name = "integerlist";
          field.Type = TType.List;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          {
            oprot.WriteListBegin(new TList(TType.List, Integerlist.Count));
            foreach (List<List<int>> _iter100 in Integerlist)
            {
              {
                oprot.WriteListBegin(new TList(TType.List, _iter100.Count));
                foreach (List<int> _iter101 in _iter100)
                {
                  {
                    oprot.WriteListBegin(new TList(TType.I32, _iter101.Count));
                    foreach (int _iter102 in _iter101)
                    {
                      oprot.WriteI32(_iter102);
                    }
                    oprot.WriteListEnd();
                  }
                }
                oprot.WriteListEnd();
              }
            }
            oprot.WriteListEnd();
          }
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("NestedListsI32x3(");
      bool __first = true;
      if (Integerlist != null && __isset.integerlist) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Integerlist: ");
        __sb.Append(Integerlist);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
